name: OnimaFaction
author: Jestiz
main: net.onima.onimafaction.OnimaFaction
version: 1.0
description: Faction
depend: [OnimaAPI]

commands:
  faction:
    aliases: [fac, f]
    description: Commande principale pour les factions.
  focus:
    description: Focus un joueur.
  teamlocation:
    aliases: tl
    description: Envoie sa position à sa team.
  eotw:
    description: Démarre ou stoppe l'eotw.
  sotw:
    description: Démarre ou stoppe le sotw.
  raidable:
    description: Démarre ou stoppe l'event raidable.
  revive:
    description: Ressucite un joueur deathban.
  logout:
    description: Se déconnecter en sécurité.
  lives:
    description: Gère les vies.
  staffchat:
    description: Met en staffchat.
    aliases: sc
  pvp:
    description: Gère le pvp timer.