name: OnimaGames
author: Jestiz
main: net.onima.onimagames.OnimaGames
version: 1.0
description: Games
depend: [OnimaAPI, OnimaFaction]

commands:
  game:
    description: Commande principale pour les events.